#spring:
#  profiles:
#    active: prod
#
#server:
#  servlet:
#    context-path: /journal

# Stop logger for particular class
#logging:
#  level:
#    com:
#      santoshkumawat:
#        journalApp:
#          service:
#            UserService: OFF

#Stop logger for whole application
#logging:
#  level:
#    root: OFF